### ISSUE TITLE
[Dungeon] Scholomance

### ISSUE THREAD

**Issue by Rephaimerino** [KurthosWoW/TrinityCore#54] opened 2018-09-09 15:35 UTC
**Description:**

Scholomance Acolytes/Neophytes cast trough game objects, ignoring LOS

**Current behaviour:**

Mobs casting through Bookcases

**Expected behaviour:**

Shouldn't

https://imgur.com/a/yvkDWpx

**Comment by HelloKitty** [comment] 2018-09-09 15:46
This behavior is likely intended. Creatures and players are suppose to be able to cast through M2 objects. Based on Subv's old work I made a PR to Trinitycore awhile back that corrected this behavior. You can see the lengthy dicussion on how this is correct and intended here: https://github.com/TrinityCore/TrinityCore/pull/18528

You can see it was actually comitted to Trinitycore here: https://github.com/TrinityCore/TrinityCore/commit/01d715eaef99e91f0959dc85fb7f69eb26d01a22

So, this is working as intended.

**Comment by HelloKitty** [comment] 2018-09-09 15:47
Closing because working as intended.

**Closed by HelloKitty** 2018-09-09 15:47 UTC
Labels: Working as Intended
